Line segment hashcode collision reduction
NetTopologySuite/NetTopologySuite pull request #608
Opened 2022-05-12 05:12 UTC by Skibisky

### Description
Line Segment GetHashCode creates collisions.
Seems to be straight lines of same length that are 10 units away in 1 axis.

Added a very simple unit test.
Added a performance test which should identify if things go bad.

Could probably increase robustness by testing lines of varying length/offset/direction.

2022-05-12 05:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NetTopologySuite/NetTopologySuite?pullRequest=608) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NetTopologySuite/NetTopologySuite?pullRequest=608) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NetTopologySuite/NetTopologySuite?pullRequest=608) it.</sub>

2022-05-12 06:32 UTC, DGuidi commented
I would like to highlight two main issues with this pull request, that personally made me not comfortable this PR to be accepted

1. The current implementation is the same [JTS code uses](https://github.com/locationtech/jts/blob/149b3890780b42836cee64b0c99c1daecb085ba2/modules/core/src/main/java/org/locationtech/jts/geom/LineSegment.java#L643), so for personal feelings I'm against introduce code differences (but we can open an issue in JTS code, of course)
2. I'm not comfortable with _unchecked_ code: but I must admit that I'm not anymore aligned with .net intrinsics, so I'm not sure that unckecked code can introduce issues with different runtimes and/or target compilation: maybe unckecked is used in other parts of NTS codebase? If it's already used, of course this second point is not valid

2022-05-12 10:34 UTC, Skibisky commented
Thanks for the link, I saw some references to JTS around. 
I will see if the hash collisions also occur in the Java environment.
The usage of 'unchecked' here permits integer overflow so that the runtime doesn't throw an exception.

2022-05-12 11:17 UTC, DGuidi commented
What I mean is: using unchecked in a codebase allow an assembly to be used in different context, as example in xamarin forms targeting iOS?

2022-05-12 11:29 UTC, airbreather commented
> What I mean is: using unchecked in a codebase allow an assembly to be used in different contexts, as example in xamarin forms targeting iOS?

`unchecked` should be fine.  It's actually the default, but this pattern is often used in places where overflow is **expected** to happen, since sometimes people turn on checking.

I would personally fix this by doing something more like
```csharp
return (_p0.X, _p0.Y, _p1.X, _p1.Y).GetHashCode();
```
but this works too

2022-05-27 08:52 UTC, Skibisky commented
JTS have made changes to LineSegment hashCode, is the submission in an acceptable state to continue?

2022-05-29 16:38 UTC, FObermaier reviewed
Remove dead code.

2022-05-30 07:29 UTC, FObermaier requested changes

2022-05-30 07:29 UTC, FObermaier commented on src/NetTopologySuite/Geometries/LineSegment.cs
>              long bits0 = BitConverter.DoubleToInt64Bits(_p0.X);
Remove dead code

2022-05-30 07:49 UTC, FObermaier approved these changes

2022-06-02 11:34 UTC, merged

2022-06-02 11:34 UTC, FObermaier commented
Thanks for your contribution