Fix VariableBuffer to handle zero distances
NetTopologySuite/NetTopologySuite pull request #700
Opened 2023-08-18 05:23 UTC by Alison-97

### Description

This patch is adopted from the fix in JTS - [Fix VariableBuffer to handle zero distances](https://github.com/locationtech/jts/pull/997)

It seeks to resolve an [issue ](https://github.com/NetTopologySuite/NetTopologySuite/issues/698) within the VariableBuffer class of the NTS library, which was previously identified and successfully addressed in the JTS library.

2023-08-18 05:23 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NetTopologySuite/NetTopologySuite?pullRequest=700) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NetTopologySuite/NetTopologySuite?pullRequest=700) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NetTopologySuite/NetTopologySuite?pullRequest=700) it.</sub>

2023-08-18 09:33 UTC, FObermaier requested changes
Thanks for you valuable contribution. Would you be so kind to port the changes to the unit test as well? Thanks

2023-08-18 09:33 UTC, FObermaier commented on src/NetTopologySuite/Operation/Buffer/VariableBuffer.cs
> +    /// Only single linestring are supported as input, since buffer widths
linestrings

2023-08-19 02:50 UTC, Alison-97 commented
> Thanks for you valuable contribution. Would you be so kind to port the changes to the unit test as well? Thanks

The unit test has been ported in

2023-08-21 06:17 UTC, FObermaier approved these changes

2023-08-21 06:18 UTC, merged