Make Coordinate Tuple friendly (Conversions and Deconstructions)
NetTopologySuite/NetTopologySuite pull request #733
Opened 2024-02-08 22:52 UTC by mehrandvd

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NetTopologySuite/NetTopologySuite/pulls) open
- [x] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository.

- [x] I have provided test coverage for my change (where applicable)

### Description
Leveraging the latest features in C#, we can define `Coordinate` variables in a more streamlined manner. I recommend the incorporation of **implicit conversion operators** and **deconstructors** to enhance usability and readability.

With a well-defined **implicit conversion operator**, we can instantiate `Coordinate` objects as follows:

```csharp
Coordinate p1 = (1, 2);
CoordinateZ p2 = (1, 2, 3);
```

Similarly, by implementing an effective **Deconstructor**, we can extract values from our `Coordinate` objects like so:

```csharp
var (x, y) = p1;
// or
var (x, _) = p1;
// or
var (x, y, z) = p1;
// or
var (x, y, _) = p1;
```
This approach not only simplifies the code but also enhances its readability and maintainability.

2024-02-08 22:53 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NetTopologySuite/NetTopologySuite?pullRequest=733) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NetTopologySuite/NetTopologySuite?pullRequest=733) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NetTopologySuite/NetTopologySuite?pullRequest=733) it.</sub>

2024-02-12 09:04 UTC, FObermaier reviewed
In general I have no objections to merging this. Why did you leave out `CoordinateZM` class?

2024-02-12 13:21 UTC, airbreather requested changes
I'm +0 on the overall idea, but I do support the idea that `CoordinateZM` should be handled consistently: either tuple support on all `Coordinate` types or none of them.

2024-02-12 13:21 UTC, airbreather commented on src/NetTopologySuite/Geometries/CoordinateM.cs
> +        }
```suggestion
        /// <summary>
        /// Implicit conversion of a <c>(double x, double y)</c> value to a <c>CoordinateM</c>.
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static implicit operator CoordinateM((double x, double y) value)
            => new CoordinateM(value.x, value.y);
        
        /// <summary>
        /// Implicit conversion of a <c>(double x, double y, double m)</c> value to a <c>CoordinateM</c>.
        /// </summary>
        /// <param name="value"></param>
        /// <returns></returns>
        public static implicit operator CoordinateM((double x, double y, double m) value)
            => new CoordinateM(value.x, value.y, value.m);

        /// <summary>
        /// Deconstructs this <c>CoordinateM</c> into its x, y and m values.
        /// </summary>
        /// <param name="x"></param>
        /// <param name="y"></param>
        /// <param name="m"></param>
        public void Deconstruct(out double x, out double y, out double m)
        {
            x = X;
            y = Y;
            m = M;
        }
```

2024-02-12 15:12 UTC, mehrandvd commented
@FObermaier I've added support for `CoordinateZM` too.

2024-02-13 11:30 UTC, airbreather approved these changes

2024-02-14 08:06 UTC, merged