Compute Iterpolation Parameters once
NetTopologySuite/NetTopologySuite pull request #757
Opened 2024-05-17 21:47 UTC by rkolka

### Prerequisites

- [x ] I have written a descriptive pull-request title
- [x ] I have verified that there are no overlapping [pull-requests](https://github.com/NetTopologySuite/NetTopologySuite/pulls) open
- [x ] I have verified that I am following the existing coding patterns and practice as demonstrated in the repository.

- [x ] I have provided test coverage for my change (where applicable)

### Description

Interpolation parameters are never changing (for a given number of vertices). ComputeIterpolationParameters can be called just once, ie `static`.

No change in behavior. 
(Although perhaps _numVerticesPerSegment is meant to be 17?)

### Discussion
If n is number of vertices per original segment then n-1 is the number of resulting segments. We might prefer the last number to be a power of 2 and _numVerticesPerSegment be 16 + 1.
If _numVerticesPerSegment-1 is a reasonably small power of 2 (eg 16 or 32) then fractions have finite representations in `double` binary and sum of parameters is exactly 1. With _numVerticesPerSegment = 16 there is a slight diff (less than 2E-16) sometimes. But even then we can make the sum exactly 1 easily. No need for division in CubicBezier.

2024-05-17 21:48 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/NetTopologySuite/NetTopologySuite?pullRequest=757) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/NetTopologySuite/NetTopologySuite?pullRequest=757) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/NetTopologySuite/NetTopologySuite?pullRequest=757) it.</sub>

2024-05-31 07:52 UTC, FObermaier requested changes
Good catch, thanks! I only have some minor change requests/suggestions.

2024-05-31 07:52 UTC, FObermaier commented on src/NetTopologySuite/Shape/CubicBezierCurve.cs
> +        private static readonly int _numVerticesPerSegment = 16;
Can we expose this as a static property and compute the interpolation parameters when it is changed?
Otherwise `const` and `NumVerticesPerSegment`

2024-05-31 07:52 UTC, FObermaier commented on src/NetTopologySuite/Shape/CubicBezierCurve.cs
>          private Coordinate[] bezierCurvePts;
`_bezierCurvePts`

2026-01-21 07:27 UTC, bjornharrtell commented
I wonder if this should be upstreamed first?

2026-05-24 19:47 UTC, closed without merging